version: "3.9"

services:
  ranker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    networks:
      default: {}
    ports:
      - 127.0.0.1:${PORT:-5000}:5000

networks:
  default:
    name: ${NETWORK_NAME:-nftgal-local}
    external: true
